remote_theme: chromatical/jekyll-materialdocs

title: LCF v1.0.1
description: Library Data Communication Framework for Terminal Applications (LCF)
copyright: <a href="http://www.bic.org.uk">Book Industry Communication</a>
logo: assets/bic-logo.png 
highlight: rouge
mdl_colors: indigo-blue 
search: true 

# Build settings
markdown: kramdown

plugins:
- jekyll-remote-theme
